name: Cross-platform compilation test

on:
  push:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "Cross.toml"
      - "src/**"
      - "build.rs"
      - ".github/workflows/crossplatform.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "Cross.toml"
      - "src/**"
      - "build.rs"
      - ".github/workflows/crossplatform.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            command: cross
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-latest
            command: cross
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            command: cargo
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
            command: cargo
          - target: x86_64-apple-darwin
            runner: macos-latest
            command: cargo
          - target: aarch64-apple-darwin
            runner: macos-latest
            command: cargo

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Setup cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: CompileTestFerronLSP-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: CompileTestFerronLSP-${{ runner.os }}-${{ matrix.target }}-

      - name: Setup NASM
        if: matrix.runner == 'windows-latest'
        uses: ilammy/setup-nasm@v1

      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross --force

      - name: Install bindgen-cli
        if: matrix.command != 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm bindgen-cli --force

      - name: Build binaries
        shell: bash
        run: |
          ${{ matrix.command }} build --verbose --target ${{ matrix.target }}
